baseURL = "http://mrriptide.github.io/bungeecord-kubernetes/"
languageCode = "en-us"
title = "Bungeecord Kubernetes"
theme = "docsy"

[markup.goldmark.renderer]
unsafe= true

[params.ui]
sidebar_menu_compact = false
